<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
Partial Class LogIn
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(LogIn))
        Me.lblUserName = New System.Windows.Forms.Label()
        Me.lblPassword = New System.Windows.Forms.Label()
        Me.LinkLabel1 = New System.Windows.Forms.LinkLabel()
        Me.btnLogIn = New System.Windows.Forms.Button()
        Me.btnClear = New System.Windows.Forms.Button()
        Me.txtUserName = New System.Windows.Forms.TextBox()
        Me.txtPassword = New System.Windows.Forms.TextBox()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.btnClose = New System.Windows.Forms.Button()
        Me.lblForgotpass = New System.Windows.Forms.LinkLabel()
        Me.ghost = New System.Windows.Forms.Label()
        Me.cboLogInNames = New System.Windows.Forms.ComboBox()
        Me.lbln = New System.Windows.Forms.Label()
        Me.lblp = New System.Windows.Forms.Label()
        Me.ShowError = New System.Windows.Forms.Timer(Me.components)
        Me.Label2 = New System.Windows.Forms.Label()
        Me.lblDrive = New System.Windows.Forms.Label()
        Me.lblSCRN = New System.Windows.Forms.Label()
        Me.BackgroundWorker1 = New System.ComponentModel.BackgroundWorker()
        Me.ProgressBar1 = New System.Windows.Forms.ProgressBar()
        Me.Label3 = New System.Windows.Forms.Label()
        Me.PictureBox1 = New System.Windows.Forms.PictureBox()
        Me.Timer1 = New System.Windows.Forms.Timer(Me.components)
        Me.lblDeciderLogin = New System.Windows.Forms.Label()
        Me.lblESDecider = New System.Windows.Forms.Label()
        Me.lblUserEmail = New System.Windows.Forms.Label()
        Me.lblEmailPassword = New System.Windows.Forms.Label()
        Me.SplashScreenManager1 = New DevExpress.XtraSplashScreen.SplashScreenManager(Me, GetType(Global.QAapp.WaitForm1), True, True)
        Me.DefaultLookAndFeel1 = New DevExpress.LookAndFeel.DefaultLookAndFeel(Me.components)
        Me.lblRegion = New System.Windows.Forms.Label()
        CType(Me.PictureBox1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'lblUserName
        '
        Me.lblUserName.AutoSize = True
        Me.lblUserName.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.lblUserName.Location = New System.Drawing.Point(50, 139)
        Me.lblUserName.Name = "lblUserName"
        Me.lblUserName.Size = New System.Drawing.Size(36, 15)
        Me.lblUserName.TabIndex = 112
        Me.lblUserName.Text = "User:"
        '
        'lblPassword
        '
        Me.lblPassword.AutoSize = True
        Me.lblPassword.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.lblPassword.Location = New System.Drawing.Point(32, 174)
        Me.lblPassword.Name = "lblPassword"
        Me.lblPassword.Size = New System.Drawing.Size(62, 15)
        Me.lblPassword.TabIndex = 113
        Me.lblPassword.Text = "Password:"
        '
        'LinkLabel1
        '
        Me.LinkLabel1.AutoSize = True
        Me.LinkLabel1.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.LinkLabel1.Location = New System.Drawing.Point(32, 209)
        Me.LinkLabel1.Name = "LinkLabel1"
        Me.LinkLabel1.Size = New System.Drawing.Size(54, 15)
        Me.LinkLabel1.TabIndex = 6
        Me.LinkLabel1.TabStop = True
        Me.LinkLabel1.Text = "Register"
        Me.LinkLabel1.Visible = False
        '
        'btnLogIn
        '
        Me.btnLogIn.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.btnLogIn.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.btnLogIn.Location = New System.Drawing.Point(17, 263)
        Me.btnLogIn.Name = "btnLogIn"
        Me.btnLogIn.Size = New System.Drawing.Size(104, 27)
        Me.btnLogIn.TabIndex = 3
        Me.btnLogIn.Text = "Log In"
        Me.btnLogIn.UseVisualStyleBackColor = True
        '
        'btnClear
        '
        Me.btnClear.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.btnClear.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.btnClear.Location = New System.Drawing.Point(157, 263)
        Me.btnClear.Name = "btnClear"
        Me.btnClear.Size = New System.Drawing.Size(104, 27)
        Me.btnClear.TabIndex = 4
        Me.btnClear.Text = "Clear"
        Me.btnClear.UseVisualStyleBackColor = True
        '
        'txtUserName
        '
        Me.txtUserName.AutoCompleteCustomSource.AddRange(New String() {"MARTHA", "JUSTIN", "KEVIN", "JENNIFER", "JULIE", "JO", "HOPE", "SHARON", "MONYELLE", "MICHAEL", "LORI", "JESSICA", "JAIME", "NOUPHONH", "FARRAD", "BETH", "JAMIE", "KENT", "BONNIE", "ROB", "KEVIN", "ROBERT", "ROB", "CALVIN", "ERICA", "MARIA", "BRENDA", "NAOMI", "CHRISTOPHER", "AMANDA", "CANDICE", "DANIEL", "CHRISTINA", "LONG", "NICOLE", "VICTORIA", "ERICK", "MIKE", "SILVIA", "MARIO", "ILISHA", "SARAH", "SONIA", "ROB", "JESSICA", "LUPE", "GINA", "KENNETH", "STANLEY", "CONSWELLA", "DONNA", "LANA", "MEREDITH", "BRIDGET", "HEIDI", "SHEMIKA", "JODY", "JAN", "NANCY", "GLORIA", "BOB", "DANIEL", "CLARENCE", "JOHNNY", "JIMMY", "CARLOS", "MICHELE", "JILL", "NATHAN", "LOUIS", "MATTHEW", "RAVEN", "CLAUDIA", "JODI", "SAED", "MICHAEL", "RAJ", "BO", "BOB", "SAVANNA", "SHARON", "JAY", "OMORO", "ALAN", "KEVIN", "PORTAL", "ADIL", "JOHN", "PENNY", "KATHRYN", "CHRISTINE", "SONIA", "LINDA", "NANCY", "BREANNA", "CATHLEEN", "STEVE", "RENNEE", "ANN", "RUSSELL", "ERIC", "MATTHEW", "NATHAN", "DENISE", "LINDA", "MICHELLE", "DER", "WAIKIKI", "AMBER", "BRANDI", "JIMMEKA", "TERRY", "JESSICA", "CHARLES", "CHRIS", "ALAN", "JILLIAN", "TAMEIKA", "GREGORY", "CHRIS", "TERI", "DAVID", "JOE", "SARAH", "RACHAEL", "LISA", "CHANDRA", "TERRY", "VERA", "JOANN", "PAMELA", "CHRISTINE", "TERRY", "JUAN", "JENNIFER", "JASON", "MATT", "RANDY", "KAYLEENE", "DAVID", "RAVI", "YESENIA", "NEIKA", "ALEXANDRIA", "RECORDS", "MATHEW", "JANINE", "CHARLES", "JOSEPH", "ALLAN", "KAREN", "MICHELLE", "NICOLE", "MEKESHIA", "PAUL", "ANN", "CHERYL", "LORI", "HARRY", "SHANTA", "MICHAEL", "CHERI", "ADREANNA", "CHRISTOPHER", "TANYA", "KRISTIE", "TAMMIE", "PHYLLIS", "JENNIFER", "FATIMAH", "FERNANDO", "LORENA", "ELIZABETH", "MICHELE", "ANITA", "NATASHA", "BELLA", "PHIL", "WENDY", "CRAIG", "KEVIN", "LAWANDA", "CHRISTINE", "ERNEST", "CHANDERLYN CACHAREL", "DIRK", "THERESA", "DETERRICA", "LESLIE", "DIONNE", "JUNKO", "RODNEY", "TIA", "ANITA", "EMILY", "DAVID", "REBECCA", "KIKI", "DENNIS", "HEATHER", "MICHAEL", "ANGELA", "WILLIE", "BRENDA", "DEBRA", "DEIDRE", "DOUGLAS", "RECORDS", "KELLY", "MICHELLE", "CHRISSY", "MANDY", "EMMANUELL", "CAROLE", "KIM", "CHERYL", "TANYA", "DREMEKA", "TEK", "CINDY", "NINA", "KELLY", "DAVID", "AMANDA", "JAMES", "KIRK", "MICHELLE", "CHRIS", "CHRIS", "VALERIE", "BHAVANI", "PAMELA", "JANA", "DELORIS", "JUDITH", "ILAND", "JARED", "JAMES", "RICHARD", "JOHN", "JOHN", "CHARLIE", "LOUIS", "GRETA", "NATALIE", "BILL", "CHARLES", "SNEHA", "JAMIE", "YOLANDA", "JULIE", "ANTONIA", "LAURA", "MATTHEW", "BONNIE", "STEVE", "RODRICK", "KANDACE", "ANTHONY", "RECORDS", "ELECTRONIC", "ANGELO", "DOUGLAS", "ELSA", "FRANSJALIF", "DEBORAH", "MEREDETH", "TERRELL", "SUSAN", "ELIZABETH", "LINDA", "CORETTA", "JAMES", "MICHELLE", "CORINNA", "MIKE", "GUSTAVO", "ROBERT", "MONIQUE", "MICHELLE", "MELISSA", "CONNIE", "HEATHER", "KELLY", "BERNICE", "SHARON", "WENDY", "TREON", "AMANDA CHRISTINE", "DEBORAH", "STEPHANIE", "BERNADETTE", "KATHLEEN", "PHILIP", "SHANE", "ASHLEY", "ROGER", "ANASTASIYA", "VANTHANA", "DAMION", "COLIN", "REBECCA", "JULIE", "STEPHANIE", "DENISE", "TREVIA", "CARLA", "WANDA", "ALEASHA", "CHRISTOPHER", "ERIKA", "DEBRA", "PUSHPA", "MICHAEL", "RITA", "LINDA", "REGINA", "RICHARD", "BRIAN", "ALAN", "EUGENE", "BEATRIS", "DEIDRE", "ELISABETH", "CAMILLE", "SARAH", "SUSAN", "WADE", "ALICE", "HANNAH", "RICHARD", "KEVIN", "JAN", "LATONIA", "ATURI", "ALFRED", "PREETHI", "SWIJI", "SAMARTH", "JACK", "KENNY", "MAX", "RICHARD", "MOHAMMED", "SYDNEY", "DAPHNE", "KIMBERLY", "NAVEEN", "RONALD", "SHAUNNA", "BRAIN", "MARTHA", "CHAITRA", "SABRINA", "KELLY", "MICHAEL", "REBEKAH", "SUJITH", "RICHARD", "WENDY", "LAURA", "PETER", "VINOTH", "NARISH", "DEBOLINA", "ARUN", "WAYNE", "GARY", "SUNDAY", "BROWNE", "JAMES", "HEENA", "NORRIS", "RAMAVATHI", "PRABHAKARAN", "ARLIE", "G", "LELIA", "DWAYNE", "MOHAMED", "MATT", "MILAN", "JIMMY", "FAITH", "RYAN", "ALEXANDRIA", "AVINASH", "NISHITH", "JAVID", "RASHMI", "RAJKUMAR", "MAUSAM", "CIARRA", "ALDO", "MOHAN", "SHENNEKA", "AUSTIN", "JACOB", "ALEXANDRA", "CRYSTAL", "CHANDRASEKHAR", "PURSHOTH", "AROKYARAJ", "NOELLE", "JAMIE", "VINAY", "SHARMILA", "MANDEEP", "SHILPA", "VEENA", "MONIQUE", "KATHLEENE", "TONYA", "MICHELLE", "BARATH", "NITHIN", "SHRUTHI", "RAJEEV", "ANTHONY", "SUHAS", "STEPHEN", "BENJAMIN", "HEENU", "PEI", "DONALD", "SARAH", "ETHAN", "LINGARAJ", "SAMPATH", "SURESH", "KONDAIAH", "MICHELLE", "AARON", "SOLOMON", "BOPANNA", "AMEENA", "BHUJANGARAJ", "DIPIN", "KARTHIYAYINI", "SHAQUITA", "GENNIE", "CARY", "MANIDIPA", "DIANA", "MOHAMMED", "SARITHA", "NADIM", "SUHASINI", "JAYASHEELA", "MAYURI", "JAYASHANKAR", "SYED", "STEPHEN", "KASONDRA", "BRITNEY", "JULIA", "PAULETTE", "CHAITRA", "SANGEETA", "MUKUND", "LAVANYA", "SHALINI", "VINAY", "AMRITA", "SOUMYA", "VARSHA", "DINESH", "MOHAMMAD", "KAYALVISHI", "SHIVA", "SUDESHNA", "HITESH", "ANIMESH", "REENA", "LUCY", "AMITH", "LISA", "SUSHMA", "SANGEETHA", "PRIYANKA", "RAMYA", "CHANDRA", "PRABHU", "ANTO", "KRITI", "PRIYANKA", "JAMES", "NALINI", "SELVIN", "WASIHA", "VISHAL", "KIMBERLY", "ROSALYNN", "WILLIAM", "TAMIKA", "CATRICE", "LASHONDA", "PACHETTE", "CARITA", "LORENE", "RYAN", "CHARLENE", "CHRISTINE", "CHRISTOPHER", "CHRISTINE", "ELIZABETH", "KEVIN", "DANIELLE", "BALAMURUGAN", "SUGIRTHAM", "VIKRANT", "ANIL", "KAVIRAJ", "MOHAN", "SHIV", "MOHAMMED", "GAVIN", "MARK", "CALVIN", "LINDA", "MAURICE", "VINUE", "SUPRIYA", "SHARMILA", "THIAGARAJAN", "SUMAN", "SHASHI", "SHWETHA", "DEEPAK", "VIJAY", "STEPHANIE", "ERIC", "RIDLEY", "MADELYN", "NANCY", "KATHERINE", "CHRISTOPHER", "JASON", "STELLA", "MURRAY", "LAURIE", "JOHN", "CLARA", "CAPRICIA", "ANDY", "REBECCA", "SCARLETT", "MARTYN", "WILLIAM", "SCOTT", "NAVEEN", "MICHAEL", "SNEHA", "SONAM", "VIJAY", "SUJITH", "CRAIG", "SENTHIL", "WILFRED", "SYLVESTER", "SHAIKH", "FRANK", "ANTOINETTE", "GWENDOLYN", "ANGEL", "DOMINIQUE", "TONYA", "ROHELIA", "CLARICE", "TEALACY", "KIMBERLY", "SHANIECE", "ROCKY", "JENNIFER", "SYED", "PRADEEPDEVA", "JASMINE", "DUANA", "MOHAMMED", "NEEKHIL", "JOY", "NEHA", "SHRUTHI", "ANKIT", "ALISHA", "TULASI", "SONALI", "CHANDAN", "DIVYA", "MOHAMMED", "SANGEETA", "SUDHA", "SANDEEP", "THADDEAUS", "REBECCA", "ASHUTOSH", "ABHISHEK", "RAVICHANDRA", "LYNA", "CHARLES", "GAYATHRI", "SUPRIYA", "KOKA", "ANIL", "VAJRESH", "DEEP", "LOHITHA", "IYAZ", "JEEVAN", "ANANTH", "PUSHPA", "AISWARYA", "SHRUTHI", "GEMSHITH", "BISWAJIT", "VARUN", "DONNA", "CHAD", "RYAN", "ASHLEY", "KIM", "HEATHER", "MAHESH", "VIVEK", "ANDREA", "SHARAD", "MAYRA", "JENNIFER", "ANAND", "SAUHEB", "BANITA", "PREETI", "MOHAMMED", "MELISSA", "SALMAN", "SRIJANA", "AJITH", "POOJA", "NICOLE", "SURYA", "RATHY", "MOHAMMED", "HYUNSEOK", "JACK", "DARREL", "MICHAEL", "EVAN", "VANISHRI", "SAPTHANAA", "ANDREW", "CRYSTAL", "CONNIE", "SARAH", "JANIS", "RICAHRD", "ERIN", "AMY", "MATTHEW", "VICTORIA", "MARIA", "BEN", "REBECCA", "DANIEL", "RAEMEL", "ANGELINA", "KELLY", "WIKTORIA", "MADDISON", "JOSEPHINE", "JOSHUA", "STEVEN", "SUSAN", "TINA", "ASHLEY", "JONATHAN", "VANISHREE", "ASHISH", "MANJU", "MEGAN", "SANDEEP", "SHWETA", "KELLY", "CARLOS", "CRAIGE", "KUSHANG", "SIVARANJAN", "HOLLY", "MANDEEP", "CORY", "LIZ", "TARA", "MELISSA", "CHARLES", "GENEVIEVE", "SHRUTI", "MOINUDDIN", "ANIL", "SUNDAR", "JOY", "HEIDI", "VAL", "SATISH", "URVASHI", "ASHLEY", "KARUN", "CHRISTINE", "JOHNSON", "YUKO", "ERNANI", "JONATHAN", "ASHLEY", "MINAKO", "SOWMYA", "JAYALATA", "PAOLO", "SCOTT", "KRYSTIE", "YUKO", "SANJEEB", "LISSA", "PAULINE", "DENNIS", "LEO", "COURTNEY", "STACEY", "REMY", "DONDRA", "MELISSA", "KARI", "KATINA", "KATHLEEN", "SHELLEY", "MICHAEL", "KRISTINE", "NAVIN", "NIKITA", "JASON", "TRAVIS", "GRAZZIANI", "ARCHANA", "NICOLE", "MICHAEL", "KATHERINE", "BRANDEE", "GENEVIEVE", "ARUN", "JESSE", "NIMISH", "ROHIT", "GAUTHAM", "VICKI", "SAI", "NIHAR", "SHAIK", "SANGEETHA", "RASHMI", "NILANJAN", "KARTHIGAN", "ESTHER", "MOHAMMED", "KANMANI", "SNEHA", "NARESH", "KLINT", "TRACEY", "TARUN", "LALMUANPUII", "AMARNATH", "THILAK", "JACKLYEN", "VIRGINIA", "MATTHEW", "KUNAL", "SHILPA", "FRANCESCA", "PRAVEEN", "AMIT", "WILLIAM", "DEREK", "JAISHREE", "LELIA", "ADDERLEY", "KATYE", "CAITLIN", "DAWN", "CHAD", "ASHOK", "JULIO", "ROBERT", "MANJULA", "BALASUBRAMANYA", "JUSTIN", "PAULETTE", "CASSANDRA", "AMANDA", "DEBJANI", "ROSBIN", "TABASSUM", "STEFANYE", "SHASHI", "MADHU", "ASHWINI", "ANURADHA", "SHWETHA", "MANEESHMISHAK", "SHIRLEY", "ALLWYN", "ISHNA", "DAVID", "ASHWIN", "PRABHU", "MARIAN", "RAVI", "STEPHEN", "SUHAS", "HARISH", "ROSYNA", "T", "ALEX", "SURESH", "VIJAY", "NITIN", "KRITHIKA", "BRIJITH", "NAVEEN", "IRFAN", "CHRISTINE", "AVINASH", "KHALID", "NISHA", "SHAIK", "SREEDEVI", "THAMARI", "VENONA", "DIANAL", "MAMATHA", "HEMAKALA", "RAJESHWARI", "TERRY", "PRADEEP", "PRUTHVI", "ARBEEN", "MOHAMMED", "SIRENA", "KATTI", "RYAN", "AGNES", "ANGELA", "TRACY", "CANDICE", "SURESH", "LALDINPUII", "IFSHAN", "SAYOOJ", "SNEHA", "SURAJ", "VINUTHA", "WILLIAM", "RACHEL", "MONISHA", "VATHSALA", "SYED", "ASHFAQUE", "PRADEEP", "KAVYASHREE", "BRITE", "SHRAVANI", "AFZAL", "NOOR", "OBETH", "AJAY", "SRIKANTH", "VENKATESH", "DAVID", "VINOD", "CHETAN", "CIARRA", "ASHWINI", "NARESH", "DIVYA", "ABHIJIT", "ARUN", "NIRUP", "PAMYAO", "ANUSHA", "SHARATH", "RAGHAVENDRA", "RASHMI", "AMRUTHA", "LEENA", "CLINTANT", "MUDDASSIR", "KARTHIK", "IMMACULATE", "KIRAN", "STACY", "ELVIS", "STELLA", "DEMETRIC", "VANESA", "TIA", "WILFRED", "JOE", "ROSHAN", "SWETHA", "RANDY", "ROBERT", "JOSH", "SHERESE", "SHAHANA", "ANITHA", "ASHA", "SANDEEP", "VINITA", "SHANKAR", "BRENT", "MISSY", "ALEX", "SHARRIS", "EYVETTE", "TERRENCE", "CARNECHA", "NAVEEN", "LATHA", "FARIYA", "LATANYA", "LAUREN", "LAURICE", "SMITA", "KRYSTAL", "TIFFANY", "DEB", "DAWN", "MELISSA", "JAMIE", "KYLA", "JENNIFER", "DANIELLE", "JESSICA", "MATTHEW", "TONIA", "SARA", "JASON", "PRAGATI", "JASMINE", "DIVYASHREE", "MARIA", "SUBHIRAJ", "ASHA", "PADMANABHAN", "SANJAY", "MOHAMMED", "MEHRIN", "RAHUL", "DHANUSHREE", "YUVARAJ", "MADHURI", "NOELLA", "LIESL", "FAIZA", "MOHIT", "KARTHIK", "BABLY", "RAM", "ARUN", "MUKESH", "SUMESH", "QUAZI", "RACHANA", "SHYLENDRA", "JOHN", "SAHANA", "TRACI", "JAYACHANDRA", "DEEPTHI", "ABHISEK", "SHAZAN", "IMRAN", "MOINUDDIN", "SANATH", "SHAIK", "MITHUN", "LAZARUS", "DHEERAJ", "APARNA", "RAHUL", "SHOAIB", "ANIMESH", "PRATIBHA", "ROPESH", "ADRIAN", "BRANDI", "TERRENCE", "IRFAN", "MOHAMMED", "LATASHA", "MARADONA", "ROHIT", "RAJU", "RITURAJ", "SWETHA", "SUSHMJITA", "REVANTH", "WILLIAM", "AMAR", "RAVI", "DAVID", "KATE", "CRAIG", "STEPHANIE", "DAVE", "SARAH", "IRENE", "JACQUE", "VIJAY", "ARON", "TAHLISHA", "DARREN", "MOSIA", "RHONDA", "KARIS", "MICHELE", "EDUARD", "CHETHAN", "DEEPAK", "CALEB", "PRASHANTH", "NIKHIL", "PEARL", "SURAJ", "CASSIAN", "NAGA", "HARISH", "DIVYA", "ABHILASH", "PEMALA", "SHAHZEEN", "EMMANUEL", "SRINATH", "NIEVEL", "TANYA", "SRINIVASAN", "KRYSTAL", "JOSEPH", "MOHAMMED", "NANDINI", "SHREEDHAR", "MANAS", "ELINO", "ARNABI", "ANJALI", "ARITHOTI", "VAISHNAVI", "MANTHENA", "VINAY", "ERICA", "SUGANYA", "RAJ", "SHALINI", "NISHANT", "BARBARA", "BECKY", "CHAUNDRA", "VICKY", "TYLER", "SOWMYA", "PHUONG", "VANNESS", "HEEYEON", "DUY", "MANOJ", "JOHNNY", "BETTINA", "CARMEN", "KIRAN", "SUZANNE", "RENUKA", "UMA", "JEFF", "STUART", "RAHUL", "SRINIVAS", "YADAV", "DINESH", "LETITIA", "MALINI", "PRASANSHA", "ORIN", "JOHN", "ZAFAR", "BIPLAB", "JASKARAN", "ERIC", "LUCIO", "SYED", "ANUREEMA", "PALMER", "ROSIO", "MOHAMMED", "DICKY", "RAJKUMAR", "DIEGO", "VIJAYENDRA", "MALINI", "MOHAMMED", "SHIVA", "TAHZEER", "PAWAN", "SHINELLE", "RAJKUMAR", "SAURABH", "RINI", "ROBIN", "SWATI", "MOHAMMED", "VEENA", "CHETHAN", "ARCHNA", "MANOJ", "MARY", "RAJATH", "SURESH", "JACQUELINE", "ASHA", "DEEPIKA", "SATYABHAMA", "NIYAZ", "SEAN", "VEENA", "ARUN", "KAVITHA", "ASMA", "KHUSBU", "NAVEEN", "MOHD", "TAMYRA", "MONA", "JINESH", "KAVITHA", "VIVEKANAD", "NGAMLUNGLIU", "JEEVA", "VIJAYALAKSHMI", "ANUP", "CIARA", "SYLVESTER", "RYAN", "PADMINI", "PRABHA", "SHRINIVAS", "LISHA", "BHAWNA", "JASMINE", "COLEMAN", "LAVANYA", "GIRISH", "MOHAMMED", "SHRAVAN", "PRIYANKA", "STAFFORD", "TEDDI", "RANDY", "KIMBERLY", "MARK", "PAUL", "SAI", "PADMANABHABS", "RAGHAVENDRA", "KASHYAP", "MAHEIN", "KHIROD", "SMITA", "HARSHITA", "CHRIS", "DEBI", "TERESA", "JILL", "TODD", "JESSICA", "MIRIAM", "REBA", "RASHMITHA", "GUNA", "ANAND", "RIJIN", "SYLVIA", "DANIEL", "LEE ANN", "STEPHANIE", "DANIEL", "PRAJU", "SHIRLY", "MOUNIKA", "SONAM", "SURESH", "VEENA", "VINAY", "RADHIKA", "BHUVANESHWARI", "REVATHI", "BOPAIAH", "DZIIZIENGUNUO", "KACY", "AMY", "FARAI", "DEREK", "BACKOUS", "TONI", "ROBIN", "DEANGELO", "SHAREEDA", "BRADY", "SUNITHA", "NILANJAN", "AMY", "SUSAN", "KIARA", "PETE", "CARLOS", "VENKATESH", "VIJAY", "JOHNSON", "BARBARA", "NIROSHAN", "VUELTA", "BETH", "CRYSTOL", "MATTHEW", "CLARISSA", "SREENIVAS", "DELPHINE", "RAYMOND", "MIRZAN", "ANURANJAN", "OLVEN", "DONN", "AFTAB", "PRAVEEN", "MOHAMMAD", "SHARON", "ROSA", "BRITTANI", "ANJANA", "SHAUTESE", "PATSY", "SHARON", "JAMIE", "SANITYA", "RAVINDRANATH", "RAJAN", "ARUN", "CAROLINE", "WENDY", "KAPRYCE", "SILVIA", "LAUREN", "PHYLLIS", "ICHINI", "MOHAMMED", "RAHUL", "VIDYASAGAR", "YAMINI", "JYOTI", "SYLVESTER", "JOHN", "SWATHI", "MOHAMMED", "SUPRIYA", "MITHUN", "SIRIYAPU", "NAVEEN", "GENEVIEVE", "REKHA", "LOKESH", "PRABHUSARAN", "ANISH", "ABILASH", "SUNEETHA", "BALDEEP", "DARSHAN", "NOELA", "MAHESHWARA", "RENEESH", "JOHNSON", "JOSE", "SANJAY", "B", "PHILIP", "TANMOY", "RAM", "ALBERT", "JILL", "JAMES", "LAKSHMANAN", "VINCENT", "PRASANNA", "KESAVA", "VERNETT", "VIJAY", "KIRAN", "FATHIMA", "MAINAO", "GANGADHARAN", "KARANDEEP", "MOHAMMED", "ANAND", "STEPHEN", "BIPIN", "RENCY", "UJJWAL", "SOWMYA", "DANIEL", "CHANDRA", "GIRISH", "PRAVEEN", "SUNIL", "SANATHAN", "SURESH", "DAN", "YOGENDERAN", "FELIX", "PRADEEP", "JALIA", "COREY", "CHARLENE", "ERIK", "FAUNA", "DEBRA", "HOLLY", "KEVIN", "BRITTANY", "SHANTILU", "SCOTT", "SILEVESTA", "TROY", "BARNEY", "TONY", "WILSON", "DAVID", "REBECCA", "PATRICK", "GAVIN", "ALEX", "MICHELLE", "JORDAN", "HARRY", "STEVEN", "GILL", "DEBRA", "GENEAN", "ADRIANNE", "VIVIN", "RAJARAM", "SHASHIDHARAN", "PRIYANKA", "POOJA", "NILUFER", "RACHEL", "AJAY", "NINA", "BRITTNEY", "BRANDY", "CADEJIA", "SHEMIKA", "DONNITA", "CHYAIRE", "CHARNITA", "TRENTEA", "SHAUN", "MOHAMED", "MANOHAR", "PASANNA", "TENOLA", "ASHWINI", "SADIQ", "THEADORA", "KANCHANA", "DOMINIC", "JAISON", "AMREEN", "MALLIKARJUNA", "MARIA", "AJAZ", "MARY", "IMMANUEL", "ANUPAMA", "ALAN", "VALERIE", "ANUJ", "KRISHNA", "CHRISTINE", "APPOLLONIA", "ANUP", "ROJA", "STEPHANIE", "SATHYA", "PRADEEP", "JESENIA", "TRENDA", "RESHMA", "GEETHANJALI", "JOHNSON", "ADRIAN", "AVINASH", "SAM", "CYNTHIA", "CLAYTON", "ANGELA", "PATRICIA", "CHRISTINA", "SHANETTA", "NICK", "VIVEK", "NITIN", "SANDEEP", "THARUN", "VARUN", "ESHA", "SUNIL", "RAKESH", "ALLEN", "MYCAL", "MARK", "SCOTT", "FRANCIS", "CHANDLER", "NICK", "STEVE", "CHRIS", "ERICA", "JOHN", "JEFF", "SHAUN", "FAITH", "TRISH", "MARK", "PETER", "CHRIS", "CEDRICK", "SMITH", "JANE", "SHAUN", "SHAWN", "RAGHAVENDRA", "PUNEETH", "MUSHTAQ", "TIFFANY", "NANCY", "NATALIE", "DENISE", "SIMONE", "JANET", "JAYASHREE", "DARCY", "TIFFANY", "WENDY", "SHIVARAMA", "TONY", "CHELSIE", "BRANDI", "HALEY", "RACHEL", "VARUN", "ASHLEY", "SREERAG", "SNEHA", "FAZIL", "SHERRYE", "LIBBY", "STEPHANIE", "MARIE", "VINAYAK", "CHARLYN", "MELISSA", "ANNABELLA", "ALEX", "AMANDA", "HANNAH", "CHAD", "JOSEPH", "DEBRA", "KIMBERLY", "DANIEL", "ADRIANA", "JENNIFER", "JAMES", "SANTINA", "JODIE", "RASHMI", "LIKITH", "DEBRA", "JIM", "MARVIN", "ROBERT", "JUDY", "JILLIAN", "CHANTELL", "CONNIE", "VICTORIA", "JAMES", "ANETRA", "ROBERT", "DENSON", "EON", "CHRIS", "SOPHIE", "GIM", "ANNA", "DIANE", "KRISTINA", "ERIC", "LISA A", "ANGEL", "KIMBERLY", "MICHELL", "BRITTANY", "TERESA", ",", ",", "KEVIN", "JOSHUA", "SRI", "RAJA", "SANTHOSH", "SARDA", "MANISHA", "UMME", "DADA", "NIJIN", "SHANIL", "PREETHI", "INDRAJITH", "DEEPTHI", "RANJAN", "DELLA", "DIMAS", "KATHY", "GRETCHEN", "ELAINE", "ALKA", "KAKALI", "VEDULA", "GITANJALI", "ALBERTO", "SARAH", "CHASTITY", "LAURENCE", "AMANDA", "HASEEB", "SUARYA", "DINESH", "HEMANTH", "NIRANJAN", "RAVINDRANATH", "AVISHEK", "ANIL", "DILIP", "DALEL", "NICOLE", "JACKIE", "SHANNON", "SAMANTHA", "MOHAMMED", "CASSIE", "LAURA", "CYNTHIA", "ADITYA", "DOMNIC", "MOHAN", "SHAFIQ", "PRIYA", "GREG", "JAMES", "KUBRA", "JANNET", "MIGUEL", "ROCKY", "MANJULA", "LARRY", "RESHMA", "PAUL", "SHYAM", "MAGDALENE", "WALTER", "QIANA", "CONDRID", "KRISTIN", "SHELINA", "JENNA", "SYLVASTIAN", "DEMETRA", "ABBEY", "BIANCA", "BRIANA", "SAGNIK", "HELEN", "AISHA", "YANNICK", "HEIDI", "MADHU", "RAJIV", "KYNTIEWS", "PRASANJIT", "JEMIMA", "KAVAN", "ISIS", "MARTIN", "KELLY", "BIJOU", "ANNAMETI", "LINDA", "BRET", "ANNA", "AARON", "ANDREW", "KEVIN", "SHEILA", "DANIELLE", "SALMAN", "CHARLES", "RACHEL", "NATHAN", "MONIKA", "CHARLOTTE", "CLAUDIA", "MARLENA", "STEPHANIE", "AIYLA", "CHAITHRA", "RAMSHEED", "KENNETH", "VALLABH", "RAJASHEKAR", "WANDA", "DIANE", "SUJAY", "IMMANUEL", "GOWTHAM", "KRISHNA", "RAJKIRAN", "KEVIN", "VINUSHA", "SARANYA", "NIKITA", "JAZMINE", "SARAI", "BRENDA", "SONIYA", "PRAKASH", "GOWTHAM", "SHRUTHI", "BRANDON", "KIARA", "RICHARD", "JAMES", "NORMAN", "ETHAN", "TESSA", "TOMMIE", "MICHAEL", "SOMAIAH", "ALI", "CHEEMALAMARRI", "KARTHIK", "MOHAMED", "ABIRAMISELVI", "MANOJ", "NITHI", "UDAYAPRIYA", "SUBHASHINI", "ELAKIYA", "MANONMANI", "PRIYA", "VENNAPUSA", "YASHWANTH", "MANOJ", "DIVYA", "PRATHIBHA", "AJMERA", "SHIMROSE", "KARTHIK", "SHAMSUNDER", "ROHAN", "JOEL", "SHRUTHI", "ROCHANA", "BANISHA", "AMIT", "SINGH", "GOENKA", "SK", "DEEPIKA", "ANANDHRAJ", "KAVYASHREE", "LISA", "CHARMAINE", "MICHAEL", "ANMOL", "FAROOQ", "ASHA", "NIANG", "JITENDRA", "ZAHID", "POOMOLI", "SATISH", "NANDINI", "KINGSTON", "DHIRU", "MOHAMMED", "LALDINPUII", "RAVIKUMAR", "ASHWA", "PREETHI", "FIONA", "REBECCA", "RUKMINI", "UMASHANKAR", "PREETHI", "HAMSA", "SAMANTHA", "PARTHIBAN", "RAJ", "PUNITH", "KARIM", "JOICE", "NANJAPPA", "MRIDUL", "NARESH", "YUVARAJ", "DARYL", "MOHAMMED", "VIJAYA", "MONISHA", "SARATH", "PRITHVI", "MEGHA", "MITHUN", "SANGEETHA", "VANLAL", "PRAVEEN", "KENNEDY", "TERENCE", "DARYL", "CHRISTINA", "LARON", "RAJESH", "VIMAL", "MAHESH", "HARISHKHANNA", "NAVEENRAJ", "PRASANTH", "CHITHRA", "PREETHI", "ASHICA", "POOJA", "NAVIN", "CHANDRA", "SULTAN", "JITENDAR", "MOHAMMED", "ELIZABETH", "MANOJ", "TELECIA", "ALEXIS", "KATARINA", "KUMAR", "HEATHER", "DIVYANANDA", "SYED", "SHEILA", "BRANCH", "NOLASCO", "ANDRES", "JODI LYNN", "BIDISHA", "RADHIKA", "NANCY", "NARAYANAPPA", "VIDHYA", "DHIVYA", "ARCHANA", "SHEENA", "SUMANTHA", "MOHAMMED", "NOEL", "DANIEL", "IYCHANDA", "STEVE", "BHARATH", "FERNANDEZ", "RANITA", "AMIT", "RAQUEL", "SAMRAT", "SCOTT", "SARALA", "EMMANUEL", "NITHYA", "PREETHY", "REVATHI", "CHETHAN", "SARANYA", "HARISH", "SANTHOSH", "MUKESHWARI", "SUSHANTH", "INFANT", "ROHIT", "BASHEER", "SHARMILA", "KUMAR", "SHYAMSUNDAR", "PRASHANTH", "UPENDER", "SHIVAKUMAR", "NIRMALA", "STEFFIGRAF", "BALAJI", "KETMI", "SABEER", "SETH", "PETER", "GURUCHARAN", "JAY", "JACK", "BILLY", "KEVIN", "DAVID", "TIMOTHY", "SUNNY", "SUGAPRIYA", "ARVIND", "PRABHAKARAN", "SATHISHKUMAR", "KARTIK", "MESIYA", "VENKATESH", "VASANTHRAJ", "NAVIN", "ANANTHA", "ANISH", "YOGARAJ", "SANDRA", "KUMARAN", "MANJUNATH", "VIJAY", "NITIN", "ALRITA", "VIRMARIE", "GUEDELUPE", "RACHEL", "EARL", "KATHLEEN", "ERIN", "KIEU", "SANJOY", "MONISHWARI", "SEETARAMAPPA", "SHWETHA", "PAVAN", "TASNEEM", "SUNIL", "SANTHOSH", "SHIMJU", "SANDEEP", "SARANYA", "PRIYA", "SACHIN", "HARISH", "THOKCHOM", "ANOOJ", "ABHINEETH", "NITASHA", "JAMES", "AMIT", "VANESSA", "RODNEY", "PUNITHA", "VINOD", "PRISCILLA", "BHARGAVA", "SANDEEP", "GADE", "CHANDRA", "USHA", "ANIL", "VINOD", "UMESH", "BHARANIDHARAN", "SANDRA", "NORA", "XAVIER", "ROBBIE", "AMIRA", "ALEX", "LIBYA", "NATASHA", "MICHAEL", "BRADEN", "AARON", "JENNIFER", "NEO", "SOPHIE", "JILL", "RASHEKA", "KEISHA", "MANIKANDAN", "DIVYATHEJA", "SHAMSHEER", "VELU", "SANA", "ARVIND", "SALEEM", "PINKI", "VINAY", "LISANDRA", "TONYA", "DAMIEN", "SAM", "RALPH", "GAVIN", "ARAN", "ZOYA", "SUBHASHINI", "YOLANDA", "ANISH", "SHAIK", "JAI", "NIVETHA", "ARTHI", "MAHALAXMI", "RAJARAJAN", "ARAVIND", "MUKESH", "KOUSHIK", "GANAPATHY", "GOVINDRAJ", "AHAMAD", "NISHA", "PRIYA", "MURALI", "SARIKA", "ANIL", "CHOEDON", "CHAITI", "ANUBRATA", "PADMA", "CHRISTY", "SHANNON", "FAATIN", "JIM", "HOLLY", "JOSIAH", "DESIRE", "RANDY", "JAMILA", "ANGIE", "SARAVANA", "SOWBHAGYA", "PRAVEEN", "SATHYA", "ASHOK", "MUTHUPANDI", "JEEVAN", "HASHMITHA", "NAVEEN", "AMALAN", "SYED", "PRAMOD", "RIZWAN", "EVANGELINE", "ANIL", "SOUMYA", "DILIP", "REX", "JOHN", "JESSICA", "VIKRAM", "PEERMOHAMED", "PATRICK", "ALEJANDRO", "ASMI", "NAIR", "SAIMA", "RIMPI", "SONIYA", "PRIYANKA", "ASHWINI", "PREMA", "MYTHILI", "MAHESWARA", "JEYANTHI", "SYED", "SAKTHIVEL", "JAYASHREE", "SEKAR", "GOMATHI", "GAUTAM", "KAVINKUMAR", "PRIYANKA", "JAGANNATAN", "VIGNESHWARAN", "GARRY", "CASSANDRA", "JOSE", "SIERRA", "BARBARA", "SHARON", "ABID", "NAVONIL", "DENNY", "PUNEETH", "ATUL", "VINOD", "FIONA", "SYNTHIA", "LAMONT", "SHERIA", "SETH", "WILLIAM", "VINAY", "SREEKANTH", "PUAL", "JOHN", "MICHELLE", "TAYLOR", "ANTHONY", "JENNIFER", "JOEL", "JING", "KHENEIM", "JAMIL", "XAVIER", "SPOORTHI", "MUNESH", "YEDLAPALLE", "MANI", "SIVAPRASAD", "SELVA", "DHANANJAYA", "ANESH", "SAMFRANKLIN", "CHANDRA", "SWATI", "PRABHAKARAN", "SURENDER", "KEERTHANA", "SHANTHA", "MONA", "SHALINI", "SUBETHA", "SAVITHA", "GOWTHAM", "SUSHMA", "GOPINATH", "PRADEEPA", "VISWANATHA", "AVINASH", "YOGESH", "TINTU", "ANJAMMA", "CHIRANJEEVI", "PRAVEEN", "MURALI", "PRAVEEN", "DHEERAJ", "VINOD", "DEEPA", "PRIYADARSHAN", "SASHIKALA", "BHANU", "REVATHI", "LEAH", "RANVEER", "RECCIA", "ADELE", "WHAMAN", "MARILOU", "MARCIA", "VIMALA", "NITHESH", "CLIFFERD", "LIJO", "PRASANTH", "GOKULRAJ", "POORNIMA", "PRAVEEN", "PRITHIVI", "PRADEEP", "SANDHIYA", "SURAJ", "SURENDRA", "POOJA", "RUKSANA", "SANJEEV", "THOMAS", "GURBIR", "BHAVANI", "ANANDRAJ", "KARTHIK", "KALI", "SWETHA", "SHIVA", "DEEPKUMAR", "UMESH", "DINESH", "SHALMA", "SELVA", "CLADIUS", "DINESH", "SASWAT", "BRIDGET", "HEATHER", "LAUREL", "KIMBERLE", "ERIC", "REKHA", "DANIELLE", "PRASAD", "GARRY", "CHRIS", "RIVIERA", "ROMEO", "RON", "JERRY", "VERONICA", "LISA", "STEVEN", "BRAIN", "JOHN", "RYAN", "BRITNI", "EDWARD", "PARIMALA", "VICKY", "JAMES", "JOSEPH", "PETER", "ROYDEN", "SCOTT", "SHAWN", "VAGARY", "JERRY", "NIKKI", "STEVE", "JOHN", "SEAN", "CAROL", "ROGER", "ALBIN", "VERONICA", "VASANTH", "CHELLA", "PRIYANKA", "ASHA", "SYED", "VINOD", "SANTHOSH", "DHANALAKSHMI", "SOUMYA", "SYED", "SUNIL", "JAGADISH", "JESSICA", "PAOLA", "WILHELMINA", "THUY", "CLEA", "ART", "SHEEMA", "KAREN", "CRYSTAL", "LORI", "SYREETA", "JOWANZA", "RAJESH", "MARIA", "PRASAN", "LOKESH", "SARAVANA", "SANDEEP", "REBECCA", "JEANETTE", "PADMAVATHI", "SCOTT", "DILIP", "NAVEEN", "DINESH", "JAVANNA", "PARESH", "DARLA", "KEERTHI", "MAHESHA", "VINOTH", "BARBARA", "TONI", "ANITA", "KERRY", "KATHRYN", "DIONNE", "MANDELA", "WILLIAM", "LENAE", "ANNE", "JACK", "SIYA", "ABBU", "MARKES", "KATE", "EDWARD", "SHANNON", "MOHAMMED", "SHAILESH", "AJIT", "KIRAN", "GERALD", "MONICA", "WILLIAM", "JAMES", "ROBERT", "SHATOIE", "SERGIO", "SUSAN", "LADONNA", "ANDREA", "AERIAL", "KARINE", "NORA", "DARLENE", "TAMIKA", "LESLEY", "TIERA", "DAVID", "NIRANJAN", "JILL", "YASHWIN", "SRINIVAS", "SYEEDA", "KARTHIK", "SUBASH", "REKHA", "SANTOSHI", "GYAN", "CHODACARADU", "AJAY", "VINOD", "SUNJITA", "ANITHA", "ERIC", "RADHAKRISHNAN", "MOHAMMED", "SHAIKH", "SHANTHI", "YUVARAJ", "NAGARAJ", "SANDHYA", "SHANKAR", "JOSHUA", "ANAND", "KANABIRAN", "SAVITHA", "HAJIRA", "AURTIN", "KUNAL", "AJAY", "VENANT", "ADARSH", "SUROJIT", "NATARAJAN", "DEVINA", "ANAND", "SANTOSH", "HUZAIF", "ISRAEL", "LISA", "BRUCE", "CHARLES", "TORRIS", "VIVIN", "ARUNACHALAM", "GEORGE", "CARTER", "ALAN", "LEE"})
        Me.txtUserName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend
        Me.txtUserName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtUserName.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.txtUserName.Location = New System.Drawing.Point(103, 130)
        Me.txtUserName.Name = "txtUserName"
        Me.txtUserName.Size = New System.Drawing.Size(214, 23)
        Me.txtUserName.TabIndex = 118
        '
        'txtPassword
        '
        Me.txtPassword.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtPassword.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.txtPassword.Location = New System.Drawing.Point(103, 167)
        Me.txtPassword.Name = "txtPassword"
        Me.txtPassword.PasswordChar = Global.Microsoft.VisualBasic.ChrW(42)
        Me.txtPassword.Size = New System.Drawing.Size(214, 23)
        Me.txtPassword.TabIndex = 2
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label1.ForeColor = System.Drawing.Color.Blue
        Me.Label1.Location = New System.Drawing.Point(124, 106)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(135, 15)
        Me.Label1.TabIndex = 120
        Me.Label1.Text = "Welcome Please Login!"
        '
        'btnClose
        '
        Me.btnClose.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.btnClose.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.btnClose.Location = New System.Drawing.Point(297, 263)
        Me.btnClose.Name = "btnClose"
        Me.btnClose.Size = New System.Drawing.Size(104, 27)
        Me.btnClose.TabIndex = 5
        Me.btnClose.Text = "Close"
        Me.btnClose.UseVisualStyleBackColor = True
        '
        'lblForgotpass
        '
        Me.lblForgotpass.AutoSize = True
        Me.lblForgotpass.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.lblForgotpass.Location = New System.Drawing.Point(10, 234)
        Me.lblForgotpass.Name = "lblForgotpass"
        Me.lblForgotpass.Size = New System.Drawing.Size(99, 15)
        Me.lblForgotpass.TabIndex = 7
        Me.lblForgotpass.TabStop = True
        Me.lblForgotpass.Text = "Forgot Password"
        Me.lblForgotpass.Visible = False
        '
        'ghost
        '
        Me.ghost.AutoSize = True
        Me.ghost.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.ghost.Location = New System.Drawing.Point(363, 169)
        Me.ghost.Name = "ghost"
        Me.ghost.Size = New System.Drawing.Size(43, 15)
        Me.ghost.TabIndex = 123
        Me.ghost.Text = "Label2"
        Me.ghost.Visible = False
        '
        'cboLogInNames
        '
        Me.cboLogInNames.AutoCompleteCustomSource.AddRange(New String() {"MARTHA", "JUSTIN", "KEVIN", "JENNIFER", "JULIE", "JO", "HOPE", "SHARON", "MONYELLE", "MICHAEL", "LORI", "JESSICA", "JAIME", "NOUPHONH", "FARRAD", "BETH", "JAMIE", "KENT", "BONNIE", "ROB", "KEVIN", "ROBERT", "ROB", "CALVIN", "ERICA", "MARIA", "BRENDA", "NAOMI", "CHRISTOPHER", "AMANDA", "CANDICE", "DANIEL", "CHRISTINA", "LONG", "NICOLE", "VICTORIA", "ERICK", "MIKE", "SILVIA", "MARIO", "ILISHA", "SARAH", "SONIA", "ROB", "JESSICA", "LUPE", "GINA", "KENNETH", "STANLEY", "CONSWELLA", "DONNA", "LANA", "MEREDITH", "BRIDGET", "HEIDI", "SHEMIKA", "JODY", "JAN", "NANCY", "GLORIA", "BOB", "DANIEL", "CLARENCE", "JOHNNY", "JIMMY", "CARLOS", "MICHELE", "JILL", "NATHAN", "LOUIS", "MATTHEW", "RAVEN", "CLAUDIA", "JODI", "SAED", "MICHAEL", "RAJ", "BO", "BOB", "SAVANNA", "SHARON", "JAY", "OMORO", "ALAN", "KEVIN", "PORTAL", "ADIL", "JOHN", "PENNY", "KATHRYN", "CHRISTINE", "SONIA", "LINDA", "NANCY", "BREANNA", "CATHLEEN", "STEVE", "RENNEE", "ANN", "RUSSELL", "ERIC", "MATTHEW", "NATHAN", "DENISE", "LINDA", "MICHELLE", "DER", "WAIKIKI", "AMBER", "BRANDI", "JIMMEKA", "TERRY", "JESSICA", "CHARLES", "CHRIS", "ALAN", "JILLIAN", "TAMEIKA", "GREGORY", "CHRIS", "TERI", "DAVID", "JOE", "SARAH", "RACHAEL", "LISA", "CHANDRA", "TERRY", "VERA", "JOANN", "PAMELA", "CHRISTINE", "TERRY", "JUAN", "JENNIFER", "JASON", "MATT", "RANDY", "KAYLEENE", "DAVID", "RAVI", "YESENIA", "NEIKA", "ALEXANDRIA", "RECORDS", "MATHEW", "JANINE", "CHARLES", "JOSEPH", "ALLAN", "KAREN", "MICHELLE", "NICOLE", "MEKESHIA", "PAUL", "ANN", "CHERYL", "LORI", "HARRY", "SHANTA", "MICHAEL", "CHERI", "ADREANNA", "CHRISTOPHER", "TANYA", "KRISTIE", "TAMMIE", "PHYLLIS", "JENNIFER", "FATIMAH", "FERNANDO", "LORENA", "ELIZABETH", "MICHELE", "ANITA", "NATASHA", "BELLA", "PHIL", "WENDY", "CRAIG", "KEVIN", "LAWANDA", "CHRISTINE", "ERNEST", "CHANDERLYN CACHAREL", "DIRK", "THERESA", "DETERRICA", "LESLIE", "DIONNE", "JUNKO", "RODNEY", "TIA", "ANITA", "EMILY", "DAVID", "REBECCA", "KIKI", "DENNIS", "HEATHER", "MICHAEL", "ANGELA", "WILLIE", "BRENDA", "DEBRA", "DEIDRE", "DOUGLAS", "RECORDS", "KELLY", "MICHELLE", "CHRISSY", "MANDY", "EMMANUELL", "CAROLE", "KIM", "CHERYL", "TANYA", "DREMEKA", "TEK", "CINDY", "NINA", "KELLY", "DAVID", "AMANDA", "JAMES", "KIRK", "MICHELLE", "CHRIS", "CHRIS", "VALERIE", "BHAVANI", "PAMELA", "JANA", "DELORIS", "JUDITH", "ILAND", "JARED", "JAMES", "RICHARD", "JOHN", "JOHN", "CHARLIE", "LOUIS", "GRETA", "NATALIE", "BILL", "CHARLES", "SNEHA", "JAMIE", "YOLANDA", "JULIE", "ANTONIA", "LAURA", "MATTHEW", "BONNIE", "STEVE", "RODRICK", "KANDACE", "ANTHONY", "RECORDS", "ELECTRONIC", "ANGELO", "DOUGLAS", "ELSA", "FRANSJALIF", "DEBORAH", "MEREDETH", "TERRELL", "SUSAN", "ELIZABETH", "LINDA", "CORETTA", "JAMES", "MICHELLE", "CORINNA", "MIKE", "GUSTAVO", "ROBERT", "MONIQUE", "MICHELLE", "MELISSA", "CONNIE", "HEATHER", "KELLY", "BERNICE", "SHARON", "WENDY", "TREON", "AMANDA CHRISTINE", "DEBORAH", "STEPHANIE", "BERNADETTE", "KATHLEEN", "PHILIP", "SHANE", "ASHLEY", "ROGER", "ANASTASIYA", "VANTHANA", "DAMION", "COLIN", "REBECCA", "JULIE", "STEPHANIE", "DENISE", "TREVIA", "CARLA", "WANDA", "ALEASHA", "CHRISTOPHER", "ERIKA", "DEBRA", "PUSHPA", "MICHAEL", "RITA", "LINDA", "REGINA", "RICHARD", "BRIAN", "ALAN", "EUGENE", "BEATRIS", "DEIDRE", "ELISABETH", "CAMILLE", "SARAH", "SUSAN", "WADE", "ALICE", "HANNAH", "RICHARD", "KEVIN", "JAN", "LATONIA", "ATURI", "ALFRED", "PREETHI", "SWIJI", "SAMARTH", "JACK", "KENNY", "MAX", "RICHARD", "MOHAMMED", "SYDNEY", "DAPHNE", "KIMBERLY", "NAVEEN", "RONALD", "SHAUNNA", "BRAIN", "MARTHA", "CHAITRA", "SABRINA", "KELLY", "MICHAEL", "REBEKAH", "SUJITH", "RICHARD", "WENDY", "LAURA", "PETER", "VINOTH", "NARISH", "DEBOLINA", "ARUN", "WAYNE", "GARY", "SUNDAY", "BROWNE", "JAMES", "HEENA", "NORRIS", "RAMAVATHI", "PRABHAKARAN", "ARLIE", "G", "LELIA", "DWAYNE", "MOHAMED", "MATT", "MILAN", "JIMMY", "FAITH", "RYAN", "ALEXANDRIA", "AVINASH", "NISHITH", "JAVID", "RASHMI", "RAJKUMAR", "MAUSAM", "CIARRA", "ALDO", "MOHAN", "SHENNEKA", "AUSTIN", "JACOB", "ALEXANDRA", "CRYSTAL", "CHANDRASEKHAR", "PURSHOTH", "AROKYARAJ", "NOELLE", "JAMIE", "VINAY", "SHARMILA", "MANDEEP", "SHILPA", "VEENA", "MONIQUE", "KATHLEENE", "TONYA", "MICHELLE", "BARATH", "NITHIN", "SHRUTHI", "RAJEEV", "ANTHONY", "SUHAS", "STEPHEN", "BENJAMIN", "HEENU", "PEI", "DONALD", "SARAH", "ETHAN", "LINGARAJ", "SAMPATH", "SURESH", "KONDAIAH", "MICHELLE", "AARON", "SOLOMON", "BOPANNA", "AMEENA", "BHUJANGARAJ", "DIPIN", "KARTHIYAYINI", "SHAQUITA", "GENNIE", "CARY", "MANIDIPA", "DIANA", "MOHAMMED", "SARITHA", "NADIM", "SUHASINI", "JAYASHEELA", "MAYURI", "JAYASHANKAR", "SYED", "STEPHEN", "KASONDRA", "BRITNEY", "JULIA", "PAULETTE", "CHAITRA", "SANGEETA", "MUKUND", "LAVANYA", "SHALINI", "VINAY", "AMRITA", "SOUMYA", "VARSHA", "DINESH", "MOHAMMAD", "KAYALVISHI", "SHIVA", "SUDESHNA", "HITESH", "ANIMESH", "REENA", "LUCY", "AMITH", "LISA", "SUSHMA", "SANGEETHA", "PRIYANKA", "RAMYA", "CHANDRA", "PRABHU", "ANTO", "KRITI", "PRIYANKA", "JAMES", "NALINI", "SELVIN", "WASIHA", "VISHAL", "KIMBERLY", "ROSALYNN", "WILLIAM", "TAMIKA", "CATRICE", "LASHONDA", "PACHETTE", "CARITA", "LORENE", "RYAN", "CHARLENE", "CHRISTINE", "CHRISTOPHER", "CHRISTINE", "ELIZABETH", "KEVIN", "DANIELLE", "BALAMURUGAN", "SUGIRTHAM", "VIKRANT", "ANIL", "KAVIRAJ", "MOHAN", "SHIV", "MOHAMMED", "GAVIN", "MARK", "CALVIN", "LINDA", "MAURICE", "VINUE", "SUPRIYA", "SHARMILA", "THIAGARAJAN", "SUMAN", "SHASHI", "SHWETHA", "DEEPAK", "VIJAY", "STEPHANIE", "ERIC", "RIDLEY", "MADELYN", "NANCY", "KATHERINE", "CHRISTOPHER", "JASON", "STELLA", "MURRAY", "LAURIE", "JOHN", "CLARA", "CAPRICIA", "ANDY", "REBECCA", "SCARLETT", "MARTYN", "WILLIAM", "SCOTT", "NAVEEN", "MICHAEL", "SNEHA", "SONAM", "VIJAY", "SUJITH", "CRAIG", "SENTHIL", "WILFRED", "SYLVESTER", "SHAIKH", "FRANK", "ANTOINETTE", "GWENDOLYN", "ANGEL", "DOMINIQUE", "TONYA", "ROHELIA", "CLARICE", "TEALACY", "KIMBERLY", "SHANIECE", "ROCKY", "JENNIFER", "SYED", "PRADEEPDEVA", "JASMINE", "DUANA", "MOHAMMED", "NEEKHIL", "JOY", "NEHA", "SHRUTHI", "ANKIT", "ALISHA", "TULASI", "SONALI", "CHANDAN", "DIVYA", "MOHAMMED", "SANGEETA", "SUDHA", "SANDEEP", "THADDEAUS", "REBECCA", "ASHUTOSH", "ABHISHEK", "RAVICHANDRA", "LYNA", "CHARLES", "GAYATHRI", "SUPRIYA", "KOKA", "ANIL", "VAJRESH", "DEEP", "LOHITHA", "IYAZ", "JEEVAN", "ANANTH", "PUSHPA", "AISWARYA", "SHRUTHI", "GEMSHITH", "BISWAJIT", "VARUN", "DONNA", "CHAD", "RYAN", "ASHLEY", "KIM", "HEATHER", "MAHESH", "VIVEK", "ANDREA", "SHARAD", "MAYRA", "JENNIFER", "ANAND", "SAUHEB", "BANITA", "PREETI", "MOHAMMED", "MELISSA", "SALMAN", "SRIJANA", "AJITH", "POOJA", "NICOLE", "SURYA", "RATHY", "MOHAMMED", "HYUNSEOK", "JACK", "DARREL", "MICHAEL", "EVAN", "VANISHRI", "SAPTHANAA", "ANDREW", "CRYSTAL", "CONNIE", "SARAH", "JANIS", "RICAHRD", "ERIN", "AMY", "MATTHEW", "VICTORIA", "MARIA", "BEN", "REBECCA", "DANIEL", "RAEMEL", "ANGELINA", "KELLY", "WIKTORIA", "MADDISON", "JOSEPHINE", "JOSHUA", "STEVEN", "SUSAN", "TINA", "ASHLEY", "JONATHAN", "VANISHREE", "ASHISH", "MANJU", "MEGAN", "SANDEEP", "SHWETA", "KELLY", "CARLOS", "CRAIGE", "KUSHANG", "SIVARANJAN", "HOLLY", "MANDEEP", "CORY", "LIZ", "TARA", "MELISSA", "CHARLES", "GENEVIEVE", "SHRUTI", "MOINUDDIN", "ANIL", "SUNDAR", "JOY", "HEIDI", "VAL", "SATISH", "URVASHI", "ASHLEY", "KARUN", "CHRISTINE", "JOHNSON", "YUKO", "ERNANI", "JONATHAN", "ASHLEY", "MINAKO", "SOWMYA", "JAYALATA", "PAOLO", "SCOTT", "KRYSTIE", "YUKO", "SANJEEB", "LISSA", "PAULINE", "DENNIS", "LEO", "COURTNEY", "STACEY", "REMY", "DONDRA", "MELISSA", "KARI", "KATINA", "KATHLEEN", "SHELLEY", "MICHAEL", "KRISTINE", "NAVIN", "NIKITA", "JASON", "TRAVIS", "GRAZZIANI", "ARCHANA", "NICOLE", "MICHAEL", "KATHERINE", "BRANDEE", "GENEVIEVE", "ARUN", "JESSE", "NIMISH", "ROHIT", "GAUTHAM", "VICKI", "SAI", "NIHAR", "SHAIK", "SANGEETHA", "RASHMI", "NILANJAN", "KARTHIGAN", "ESTHER", "MOHAMMED", "KANMANI", "SNEHA", "NARESH", "KLINT", "TRACEY", "TARUN", "LALMUANPUII", "AMARNATH", "THILAK", "JACKLYEN", "VIRGINIA", "MATTHEW", "KUNAL", "SHILPA", "FRANCESCA", "PRAVEEN", "AMIT", "WILLIAM", "DEREK", "JAISHREE", "LELIA", "ADDERLEY", "KATYE", "CAITLIN", "DAWN", "CHAD", "ASHOK", "JULIO", "ROBERT", "MANJULA", "BALASUBRAMANYA", "JUSTIN", "PAULETTE", "CASSANDRA", "AMANDA", "DEBJANI", "ROSBIN", "TABASSUM", "STEFANYE", "SHASHI", "MADHU", "ASHWINI", "ANURADHA", "SHWETHA", "MANEESHMISHAK", "SHIRLEY", "ALLWYN", "ISHNA", "DAVID", "ASHWIN", "PRABHU", "MARIAN", "RAVI", "STEPHEN", "SUHAS", "HARISH", "ROSYNA", "T", "ALEX", "SURESH", "VIJAY", "NITIN", "KRITHIKA", "BRIJITH", "NAVEEN", "IRFAN", "CHRISTINE", "AVINASH", "KHALID", "NISHA", "SHAIK", "SREEDEVI", "THAMARI", "VENONA", "DIANAL", "MAMATHA", "HEMAKALA", "RAJESHWARI", "TERRY", "PRADEEP", "PRUTHVI", "ARBEEN", "MOHAMMED", "SIRENA", "KATTI", "RYAN", "AGNES", "ANGELA", "TRACY", "CANDICE", "SURESH", "LALDINPUII", "IFSHAN", "SAYOOJ", "SNEHA", "SURAJ", "VINUTHA", "WILLIAM", "RACHEL", "MONISHA", "VATHSALA", "SYED", "ASHFAQUE", "PRADEEP", "KAVYASHREE", "BRITE", "SHRAVANI", "AFZAL", "NOOR", "OBETH", "AJAY", "SRIKANTH", "VENKATESH", "DAVID", "VINOD", "CHETAN", "CIARRA", "ASHWINI", "NARESH", "DIVYA", "ABHIJIT", "ARUN", "NIRUP", "PAMYAO", "ANUSHA", "SHARATH", "RAGHAVENDRA", "RASHMI", "AMRUTHA", "LEENA", "CLINTANT", "MUDDASSIR", "KARTHIK", "IMMACULATE", "KIRAN", "STACY", "ELVIS", "STELLA", "DEMETRIC", "VANESA", "TIA", "WILFRED", "JOE", "ROSHAN", "SWETHA", "RANDY", "ROBERT", "JOSH", "SHERESE", "SHAHANA", "ANITHA", "ASHA", "SANDEEP", "VINITA", "SHANKAR", "BRENT", "MISSY", "ALEX", "SHARRIS", "EYVETTE", "TERRENCE", "CARNECHA", "NAVEEN", "LATHA", "FARIYA", "LATANYA", "LAUREN", "LAURICE", "SMITA", "KRYSTAL", "TIFFANY", "DEB", "DAWN", "MELISSA", "JAMIE", "KYLA", "JENNIFER", "DANIELLE", "JESSICA", "MATTHEW", "TONIA", "SARA", "JASON", "PRAGATI", "JASMINE", "DIVYASHREE", "MARIA", "SUBHIRAJ", "ASHA", "PADMANABHAN", "SANJAY", "MOHAMMED", "MEHRIN", "RAHUL", "DHANUSHREE", "YUVARAJ", "MADHURI", "NOELLA", "LIESL", "FAIZA", "MOHIT", "KARTHIK", "BABLY", "RAM", "ARUN", "MUKESH", "SUMESH", "QUAZI", "RACHANA", "SHYLENDRA", "JOHN", "SAHANA", "TRACI", "JAYACHANDRA", "DEEPTHI", "ABHISEK", "SHAZAN", "IMRAN", "MOINUDDIN", "SANATH", "SHAIK", "MITHUN", "LAZARUS", "DHEERAJ", "APARNA", "RAHUL", "SHOAIB", "ANIMESH", "PRATIBHA", "ROPESH", "ADRIAN", "BRANDI", "TERRENCE", "IRFAN", "MOHAMMED", "LATASHA", "MARADONA", "ROHIT", "RAJU", "RITURAJ", "SWETHA", "SUSHMJITA", "REVANTH", "WILLIAM", "AMAR", "RAVI", "DAVID", "KATE", "CRAIG", "STEPHANIE", "DAVE", "SARAH", "IRENE", "JACQUE", "VIJAY", "ARON", "TAHLISHA", "DARREN", "MOSIA", "RHONDA", "KARIS", "MICHELE", "EDUARD", "CHETHAN", "DEEPAK", "CALEB", "PRASHANTH", "NIKHIL", "PEARL", "SURAJ", "CASSIAN", "NAGA", "HARISH", "DIVYA", "ABHILASH", "PEMALA", "SHAHZEEN", "EMMANUEL", "SRINATH", "NIEVEL", "TANYA", "SRINIVASAN", "KRYSTAL", "JOSEPH", "MOHAMMED", "NANDINI", "SHREEDHAR", "MANAS", "ELINO", "ARNABI", "ANJALI", "ARITHOTI", "VAISHNAVI", "MANTHENA", "VINAY", "ERICA", "SUGANYA", "RAJ", "SHALINI", "NISHANT", "BARBARA", "BECKY", "CHAUNDRA", "VICKY", "TYLER", "SOWMYA", "PHUONG", "VANNESS", "HEEYEON", "DUY", "MANOJ", "JOHNNY", "BETTINA", "CARMEN", "KIRAN", "SUZANNE", "RENUKA", "UMA", "JEFF", "STUART", "RAHUL", "SRINIVAS", "YADAV", "DINESH", "LETITIA", "MALINI", "PRASANSHA", "ORIN", "JOHN", "ZAFAR", "BIPLAB", "JASKARAN", "ERIC", "LUCIO", "SYED", "ANUREEMA", "PALMER", "ROSIO", "MOHAMMED", "DICKY", "RAJKUMAR", "DIEGO", "VIJAYENDRA", "MALINI", "MOHAMMED", "SHIVA", "TAHZEER", "PAWAN", "SHINELLE", "RAJKUMAR", "SAURABH", "RINI", "ROBIN", "SWATI", "MOHAMMED", "VEENA", "CHETHAN", "ARCHNA", "MANOJ", "MARY", "RAJATH", "SURESH", "JACQUELINE", "ASHA", "DEEPIKA", "SATYABHAMA", "NIYAZ", "SEAN", "VEENA", "ARUN", "KAVITHA", "ASMA", "KHUSBU", "NAVEEN", "MOHD", "TAMYRA", "MONA", "JINESH", "KAVITHA", "VIVEKANAD", "NGAMLUNGLIU", "JEEVA", "VIJAYALAKSHMI", "ANUP", "CIARA", "SYLVESTER", "RYAN", "PADMINI", "PRABHA", "SHRINIVAS", "LISHA", "BHAWNA", "JASMINE", "COLEMAN", "LAVANYA", "GIRISH", "MOHAMMED", "SHRAVAN", "PRIYANKA", "STAFFORD", "TEDDI", "RANDY", "KIMBERLY", "MARK", "PAUL", "SAI", "PADMANABHABS", "RAGHAVENDRA", "KASHYAP", "MAHEIN", "KHIROD", "SMITA", "HARSHITA", "CHRIS", "DEBI", "TERESA", "JILL", "TODD", "JESSICA", "MIRIAM", "REBA", "RASHMITHA", "GUNA", "ANAND", "RIJIN", "SYLVIA", "DANIEL", "LEE ANN", "STEPHANIE", "DANIEL", "PRAJU", "SHIRLY", "MOUNIKA", "SONAM", "SURESH", "VEENA", "VINAY", "RADHIKA", "BHUVANESHWARI", "REVATHI", "BOPAIAH", "DZIIZIENGUNUO", "KACY", "AMY", "FARAI", "DEREK", "BACKOUS", "TONI", "ROBIN", "DEANGELO", "SHAREEDA", "BRADY", "SUNITHA", "NILANJAN", "AMY", "SUSAN", "KIARA", "PETE", "CARLOS", "VENKATESH", "VIJAY", "JOHNSON", "BARBARA", "NIROSHAN", "VUELTA", "BETH", "CRYSTOL", "MATTHEW", "CLARISSA", "SREENIVAS", "DELPHINE", "RAYMOND", "MIRZAN", "ANURANJAN", "OLVEN", "DONN", "AFTAB", "PRAVEEN", "MOHAMMAD", "SHARON", "ROSA", "BRITTANI", "ANJANA", "SHAUTESE", "PATSY", "SHARON", "JAMIE", "SANITYA", "RAVINDRANATH", "RAJAN", "ARUN", "CAROLINE", "WENDY", "KAPRYCE", "SILVIA", "LAUREN", "PHYLLIS", "ICHINI", "MOHAMMED", "RAHUL", "VIDYASAGAR", "YAMINI", "JYOTI", "SYLVESTER", "JOHN", "SWATHI", "MOHAMMED", "SUPRIYA", "MITHUN", "SIRIYAPU", "NAVEEN", "GENEVIEVE", "REKHA", "LOKESH", "PRABHUSARAN", "ANISH", "ABILASH", "SUNEETHA", "BALDEEP", "DARSHAN", "NOELA", "MAHESHWARA", "RENEESH", "JOHNSON", "JOSE", "SANJAY", "B", "PHILIP", "TANMOY", "RAM", "ALBERT", "JILL", "JAMES", "LAKSHMANAN", "VINCENT", "PRASANNA", "KESAVA", "VERNETT", "VIJAY", "KIRAN", "FATHIMA", "MAINAO", "GANGADHARAN", "KARANDEEP", "MOHAMMED", "ANAND", "STEPHEN", "BIPIN", "RENCY", "UJJWAL", "SOWMYA", "DANIEL", "CHANDRA", "GIRISH", "PRAVEEN", "SUNIL", "SANATHAN", "SURESH", "DAN", "YOGENDERAN", "FELIX", "PRADEEP", "JALIA", "COREY", "CHARLENE", "ERIK", "FAUNA", "DEBRA", "HOLLY", "KEVIN", "BRITTANY", "SHANTILU", "SCOTT", "SILEVESTA", "TROY", "BARNEY", "TONY", "WILSON", "DAVID", "REBECCA", "PATRICK", "GAVIN", "ALEX", "MICHELLE", "JORDAN", "HARRY", "STEVEN", "GILL", "DEBRA", "GENEAN", "ADRIANNE", "VIVIN", "RAJARAM", "SHASHIDHARAN", "PRIYANKA", "POOJA", "NILUFER", "RACHEL", "AJAY", "NINA", "BRITTNEY", "BRANDY", "CADEJIA", "SHEMIKA", "DONNITA", "CHYAIRE", "CHARNITA", "TRENTEA", "SHAUN", "MOHAMED", "MANOHAR", "PASANNA", "TENOLA", "ASHWINI", "SADIQ", "THEADORA", "KANCHANA", "DOMINIC", "JAISON", "AMREEN", "MALLIKARJUNA", "MARIA", "AJAZ", "MARY", "IMMANUEL", "ANUPAMA", "ALAN", "VALERIE", "ANUJ", "KRISHNA", "CHRISTINE", "APPOLLONIA", "ANUP", "ROJA", "STEPHANIE", "SATHYA", "PRADEEP", "JESENIA", "TRENDA", "RESHMA", "GEETHANJALI", "JOHNSON", "ADRIAN", "AVINASH", "SAM", "CYNTHIA", "CLAYTON", "ANGELA", "PATRICIA", "CHRISTINA", "SHANETTA", "NICK", "VIVEK", "NITIN", "SANDEEP", "THARUN", "VARUN", "ESHA", "SUNIL", "RAKESH", "ALLEN", "MYCAL", "MARK", "SCOTT", "FRANCIS", "CHANDLER", "NICK", "STEVE", "CHRIS", "ERICA", "JOHN", "JEFF", "SHAUN", "FAITH", "TRISH", "MARK", "PETER", "CHRIS", "CEDRICK", "SMITH", "JANE", "SHAUN", "SHAWN", "RAGHAVENDRA", "PUNEETH", "MUSHTAQ", "TIFFANY", "NANCY", "NATALIE", "DENISE", "SIMONE", "JANET", "JAYASHREE", "DARCY", "TIFFANY", "WENDY", "SHIVARAMA", "TONY", "CHELSIE", "BRANDI", "HALEY", "RACHEL", "VARUN", "ASHLEY", "SREERAG", "SNEHA", "FAZIL", "SHERRYE", "LIBBY", "STEPHANIE", "MARIE", "VINAYAK", "CHARLYN", "MELISSA", "ANNABELLA", "ALEX", "AMANDA", "HANNAH", "CHAD", "JOSEPH", "DEBRA", "KIMBERLY", "DANIEL", "ADRIANA", "JENNIFER", "JAMES", "SANTINA", "JODIE", "RASHMI", "LIKITH", "DEBRA", "JIM", "MARVIN", "ROBERT", "JUDY", "JILLIAN", "CHANTELL", "CONNIE", "VICTORIA", "JAMES", "ANETRA", "ROBERT", "DENSON", "EON", "CHRIS", "SOPHIE", "GIM", "ANNA", "DIANE", "KRISTINA", "ERIC", "LISA A", "ANGEL", "KIMBERLY", "MICHELL", "BRITTANY", "TERESA", ",", ",", "KEVIN", "JOSHUA", "SRI", "RAJA", "SANTHOSH", "SARDA", "MANISHA", "UMME", "DADA", "NIJIN", "SHANIL", "PREETHI", "INDRAJITH", "DEEPTHI", "RANJAN", "DELLA", "DIMAS", "KATHY", "GRETCHEN", "ELAINE", "ALKA", "KAKALI", "VEDULA", "GITANJALI", "ALBERTO", "SARAH", "CHASTITY", "LAURENCE", "AMANDA", "HASEEB", "SUARYA", "DINESH", "HEMANTH", "NIRANJAN", "RAVINDRANATH", "AVISHEK", "ANIL", "DILIP", "DALEL", "NICOLE", "JACKIE", "SHANNON", "SAMANTHA", "MOHAMMED", "CASSIE", "LAURA", "CYNTHIA", "ADITYA", "DOMNIC", "MOHAN", "SHAFIQ", "PRIYA", "GREG", "JAMES", "KUBRA", "JANNET", "MIGUEL", "ROCKY", "MANJULA", "LARRY", "RESHMA", "PAUL", "SHYAM", "MAGDALENE", "WALTER", "QIANA", "CONDRID", "KRISTIN", "SHELINA", "JENNA", "SYLVASTIAN", "DEMETRA", "ABBEY", "BIANCA", "BRIANA", "SAGNIK", "HELEN", "AISHA", "YANNICK", "HEIDI", "MADHU", "RAJIV", "KYNTIEWS", "PRASANJIT", "JEMIMA", "KAVAN", "ISIS", "MARTIN", "KELLY", "BIJOU", "ANNAMETI", "LINDA", "BRET", "ANNA", "AARON", "ANDREW", "KEVIN", "SHEILA", "DANIELLE", "SALMAN", "CHARLES", "RACHEL", "NATHAN", "MONIKA", "CHARLOTTE", "CLAUDIA", "MARLENA", "STEPHANIE", "AIYLA", "CHAITHRA", "RAMSHEED", "KENNETH", "VALLABH", "RAJASHEKAR", "WANDA", "DIANE", "SUJAY", "IMMANUEL", "GOWTHAM", "KRISHNA", "RAJKIRAN", "KEVIN", "VINUSHA", "SARANYA", "NIKITA", "JAZMINE", "SARAI", "BRENDA", "SONIYA", "PRAKASH", "GOWTHAM", "SHRUTHI", "BRANDON", "KIARA", "RICHARD", "JAMES", "NORMAN", "ETHAN", "TESSA", "TOMMIE", "MICHAEL", "SOMAIAH", "ALI", "CHEEMALAMARRI", "KARTHIK", "MOHAMED", "ABIRAMISELVI", "MANOJ", "NITHI", "UDAYAPRIYA", "SUBHASHINI", "ELAKIYA", "MANONMANI", "PRIYA", "VENNAPUSA", "YASHWANTH", "MANOJ", "DIVYA", "PRATHIBHA", "AJMERA", "SHIMROSE", "KARTHIK", "SHAMSUNDER", "ROHAN", "JOEL", "SHRUTHI", "ROCHANA", "BANISHA", "AMIT", "SINGH", "GOENKA", "SK", "DEEPIKA", "ANANDHRAJ", "KAVYASHREE", "LISA", "CHARMAINE", "MICHAEL", "ANMOL", "FAROOQ", "ASHA", "NIANG", "JITENDRA", "ZAHID", "POOMOLI", "SATISH", "NANDINI", "KINGSTON", "DHIRU", "MOHAMMED", "LALDINPUII", "RAVIKUMAR", "ASHWA", "PREETHI", "FIONA", "REBECCA", "RUKMINI", "UMASHANKAR", "PREETHI", "HAMSA", "SAMANTHA", "PARTHIBAN", "RAJ", "PUNITH", "KARIM", "JOICE", "NANJAPPA", "MRIDUL", "NARESH", "YUVARAJ", "DARYL", "MOHAMMED", "VIJAYA", "MONISHA", "SARATH", "PRITHVI", "MEGHA", "MITHUN", "SANGEETHA", "VANLAL", "PRAVEEN", "KENNEDY", "TERENCE", "DARYL", "CHRISTINA", "LARON", "RAJESH", "VIMAL", "MAHESH", "HARISHKHANNA", "NAVEENRAJ", "PRASANTH", "CHITHRA", "PREETHI", "ASHICA", "POOJA", "NAVIN", "CHANDRA", "SULTAN", "JITENDAR", "MOHAMMED", "ELIZABETH", "MANOJ", "TELECIA", "ALEXIS", "KATARINA", "KUMAR", "HEATHER", "DIVYANANDA", "SYED", "SHEILA", "BRANCH", "NOLASCO", "ANDRES", "JODI LYNN", "BIDISHA", "RADHIKA", "NANCY", "NARAYANAPPA", "VIDHYA", "DHIVYA", "ARCHANA", "SHEENA", "SUMANTHA", "MOHAMMED", "NOEL", "DANIEL", "IYCHANDA", "STEVE", "BHARATH", "FERNANDEZ", "RANITA", "AMIT", "RAQUEL", "SAMRAT", "SCOTT", "SARALA", "EMMANUEL", "NITHYA", "PREETHY", "REVATHI", "CHETHAN", "SARANYA", "HARISH", "SANTHOSH", "MUKESHWARI", "SUSHANTH", "INFANT", "ROHIT", "BASHEER", "SHARMILA", "KUMAR", "SHYAMSUNDAR", "PRASHANTH", "UPENDER", "SHIVAKUMAR", "NIRMALA", "STEFFIGRAF", "BALAJI", "KETMI", "SABEER", "SETH", "PETER", "GURUCHARAN", "JAY", "JACK", "BILLY", "KEVIN", "DAVID", "TIMOTHY", "SUNNY", "SUGAPRIYA", "ARVIND", "PRABHAKARAN", "SATHISHKUMAR", "KARTIK", "MESIYA", "VENKATESH", "VASANTHRAJ", "NAVIN", "ANANTHA", "ANISH", "YOGARAJ", "SANDRA", "KUMARAN", "MANJUNATH", "VIJAY", "NITIN", "ALRITA", "VIRMARIE", "GUEDELUPE", "RACHEL", "EARL", "KATHLEEN", "ERIN", "KIEU", "SANJOY", "MONISHWARI", "SEETARAMAPPA", "SHWETHA", "PAVAN", "TASNEEM", "SUNIL", "SANTHOSH", "SHIMJU", "SANDEEP", "SARANYA", "PRIYA", "SACHIN", "HARISH", "THOKCHOM", "ANOOJ", "ABHINEETH", "NITASHA", "JAMES", "AMIT", "VANESSA", "RODNEY", "PUNITHA", "VINOD", "PRISCILLA", "BHARGAVA", "SANDEEP", "GADE", "CHANDRA", "USHA", "ANIL", "VINOD", "UMESH", "BHARANIDHARAN", "SANDRA", "NORA", "XAVIER", "ROBBIE", "AMIRA", "ALEX", "LIBYA", "NATASHA", "MICHAEL", "BRADEN", "AARON", "JENNIFER", "NEO", "SOPHIE", "JILL", "RASHEKA", "KEISHA", "MANIKANDAN", "DIVYATHEJA", "SHAMSHEER", "VELU", "SANA", "ARVIND", "SALEEM", "PINKI", "VINAY", "LISANDRA", "TONYA", "DAMIEN", "SAM", "RALPH", "GAVIN", "ARAN", "ZOYA", "SUBHASHINI", "YOLANDA", "ANISH", "SHAIK", "JAI", "NIVETHA", "ARTHI", "MAHALAXMI", "RAJARAJAN", "ARAVIND", "MUKESH", "KOUSHIK", "GANAPATHY", "GOVINDRAJ", "AHAMAD", "NISHA", "PRIYA", "MURALI", "SARIKA", "ANIL", "CHOEDON", "CHAITI", "ANUBRATA", "PADMA", "CHRISTY", "SHANNON", "FAATIN", "JIM", "HOLLY", "JOSIAH", "DESIRE", "RANDY", "JAMILA", "ANGIE", "SARAVANA", "SOWBHAGYA", "PRAVEEN", "SATHYA", "ASHOK", "MUTHUPANDI", "JEEVAN", "HASHMITHA", "NAVEEN", "AMALAN", "SYED", "PRAMOD", "RIZWAN", "EVANGELINE", "ANIL", "SOUMYA", "DILIP", "REX", "JOHN", "JESSICA", "VIKRAM", "PEERMOHAMED", "PATRICK", "ALEJANDRO", "ASMI", "NAIR", "SAIMA", "RIMPI", "SONIYA", "PRIYANKA", "ASHWINI", "PREMA", "MYTHILI", "MAHESWARA", "JEYANTHI", "SYED", "SAKTHIVEL", "JAYASHREE", "SEKAR", "GOMATHI", "GAUTAM", "KAVINKUMAR", "PRIYANKA", "JAGANNATAN", "VIGNESHWARAN", "GARRY", "CASSANDRA", "JOSE", "SIERRA", "BARBARA", "SHARON", "ABID", "NAVONIL", "DENNY", "PUNEETH", "ATUL", "VINOD", "FIONA", "SYNTHIA", "LAMONT", "SHERIA", "SETH", "WILLIAM", "VINAY", "SREEKANTH", "PUAL", "JOHN", "MICHELLE", "TAYLOR", "ANTHONY", "JENNIFER", "JOEL", "JING", "KHENEIM", "JAMIL", "XAVIER", "SPOORTHI", "MUNESH", "YEDLAPALLE", "MANI", "SIVAPRASAD", "SELVA", "DHANANJAYA", "ANESH", "SAMFRANKLIN", "CHANDRA", "SWATI", "PRABHAKARAN", "SURENDER", "KEERTHANA", "SHANTHA", "MONA", "SHALINI", "SUBETHA", "SAVITHA", "GOWTHAM", "SUSHMA", "GOPINATH", "PRADEEPA", "VISWANATHA", "AVINASH", "YOGESH", "TINTU", "ANJAMMA", "CHIRANJEEVI", "PRAVEEN", "MURALI", "PRAVEEN", "DHEERAJ", "VINOD", "DEEPA", "PRIYADARSHAN", "SASHIKALA", "BHANU", "REVATHI", "LEAH", "RANVEER", "RECCIA", "ADELE", "WHAMAN", "MARILOU", "MARCIA", "VIMALA", "NITHESH", "CLIFFERD", "LIJO", "PRASANTH", "GOKULRAJ", "POORNIMA", "PRAVEEN", "PRITHIVI", "PRADEEP", "SANDHIYA", "SURAJ", "SURENDRA", "POOJA", "RUKSANA", "SANJEEV", "THOMAS", "GURBIR", "BHAVANI", "ANANDRAJ", "KARTHIK", "KALI", "SWETHA", "SHIVA", "DEEPKUMAR", "UMESH", "DINESH", "SHALMA", "SELVA", "CLADIUS", "DINESH", "SASWAT", "BRIDGET", "HEATHER", "LAUREL", "KIMBERLE", "ERIC", "REKHA", "DANIELLE", "PRASAD", "GARRY", "CHRIS", "RIVIERA", "ROMEO", "RON", "JERRY", "VERONICA", "LISA", "STEVEN", "BRAIN", "JOHN", "RYAN", "BRITNI", "EDWARD", "PARIMALA", "VICKY", "JAMES", "JOSEPH", "PETER", "ROYDEN", "SCOTT", "SHAWN", "VAGARY", "JERRY", "NIKKI", "STEVE", "JOHN", "SEAN", "CAROL", "ROGER", "ALBIN", "VERONICA", "VASANTH", "CHELLA", "PRIYANKA", "ASHA", "SYED", "VINOD", "SANTHOSH", "DHANALAKSHMI", "SOUMYA", "SYED", "SUNIL", "JAGADISH", "JESSICA", "PAOLA", "WILHELMINA", "THUY", "CLEA", "ART", "SHEEMA", "KAREN", "CRYSTAL", "LORI", "SYREETA", "JOWANZA", "RAJESH", "MARIA", "PRASAN", "LOKESH", "SARAVANA", "SANDEEP", "REBECCA", "JEANETTE", "PADMAVATHI", "SCOTT", "DILIP", "NAVEEN", "DINESH", "JAVANNA", "PARESH", "DARLA", "KEERTHI", "MAHESHA", "VINOTH", "BARBARA", "TONI", "ANITA", "KERRY", "KATHRYN", "DIONNE", "MANDELA", "WILLIAM", "LENAE", "ANNE", "JACK", "SIYA", "ABBU", "MARKES", "KATE", "EDWARD", "SHANNON", "MOHAMMED", "SHAILESH", "AJIT", "KIRAN", "GERALD", "MONICA", "WILLIAM", "JAMES", "ROBERT", "SHATOIE", "SERGIO", "SUSAN", "LADONNA", "ANDREA", "AERIAL", "KARINE", "NORA", "DARLENE", "TAMIKA", "LESLEY", "TIERA", "DAVID", "NIRANJAN", "JILL", "YASHWIN", "SRINIVAS", "SYEEDA", "KARTHIK", "SUBASH", "REKHA", "SANTOSHI", "GYAN", "CHODACARADU", "AJAY", "VINOD", "SUNJITA", "ANITHA", "ERIC", "RADHAKRISHNAN", "MOHAMMED", "SHAIKH", "SHANTHI", "YUVARAJ", "NAGARAJ", "SANDHYA", "SHANKAR", "JOSHUA", "ANAND", "KANABIRAN", "SAVITHA", "HAJIRA", "AURTIN", "KUNAL", "AJAY", "VENANT", "ADARSH", "SUROJIT", "NATARAJAN", "DEVINA", "ANAND", "SANTOSH", "HUZAIF", "ISRAEL", "LISA", "BRUCE", "CHARLES", "TORRIS", "VIVIN", "ARUNACHALAM", "GEORGE", "CARTER", "ALAN", "LEE"})
        Me.cboLogInNames.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend
        Me.cboLogInNames.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems
        Me.cboLogInNames.BackColor = System.Drawing.SystemColors.MenuBar
        Me.cboLogInNames.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.cboLogInNames.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.cboLogInNames.FormattingEnabled = True
        Me.cboLogInNames.Location = New System.Drawing.Point(103, 130)
        Me.cboLogInNames.MaxDropDownItems = 1
        Me.cboLogInNames.Name = "cboLogInNames"
        Me.cboLogInNames.Size = New System.Drawing.Size(214, 23)
        Me.cboLogInNames.Sorted = True
        Me.cboLogInNames.TabIndex = 1
        Me.cboLogInNames.Text = "Type Here..."
        '
        'lbln
        '
        Me.lbln.AutoSize = True
        Me.lbln.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.lbln.Location = New System.Drawing.Point(363, 116)
        Me.lbln.Name = "lbln"
        Me.lbln.Size = New System.Drawing.Size(43, 15)
        Me.lbln.TabIndex = 125
        Me.lbln.Text = "Label2"
        Me.lbln.Visible = False
        '
        'lblp
        '
        Me.lblp.AutoSize = True
        Me.lblp.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.lblp.Location = New System.Drawing.Point(363, 148)
        Me.lblp.Name = "lblp"
        Me.lblp.Size = New System.Drawing.Size(43, 15)
        Me.lblp.TabIndex = 126
        Me.lblp.Text = "Label3"
        Me.lblp.Visible = False
        '
        'ShowError
        '
        Me.ShowError.Interval = 2000
        '
        'Label2
        '
        Me.Label2.AutoSize = True
        Me.Label2.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label2.ForeColor = System.Drawing.SystemColors.ActiveCaptionText
        Me.Label2.Location = New System.Drawing.Point(124, 234)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(96, 15)
        Me.Label2.TabIndex = 127
        Me.Label2.Text = "last Update: N/a"
        Me.Label2.Visible = False
        '
        'lblDrive
        '
        Me.lblDrive.AutoSize = True
        Me.lblDrive.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.lblDrive.Location = New System.Drawing.Point(387, 194)
        Me.lblDrive.Name = "lblDrive"
        Me.lblDrive.Size = New System.Drawing.Size(14, 15)
        Me.lblDrive.TabIndex = 128
        Me.lblDrive.Text = "2"
        Me.lblDrive.Visible = False
        '
        'lblSCRN
        '
        Me.lblSCRN.AutoSize = True
        Me.lblSCRN.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.lblSCRN.Location = New System.Drawing.Point(363, 194)
        Me.lblSCRN.Name = "lblSCRN"
        Me.lblSCRN.Size = New System.Drawing.Size(14, 15)
        Me.lblSCRN.TabIndex = 129
        Me.lblSCRN.Text = "1"
        Me.lblSCRN.Visible = False
        '
        'BackgroundWorker1
        '
        Me.BackgroundWorker1.WorkerReportsProgress = True
        '
        'ProgressBar1
        '
        Me.ProgressBar1.Location = New System.Drawing.Point(261, 306)
        Me.ProgressBar1.Name = "ProgressBar1"
        Me.ProgressBar1.Size = New System.Drawing.Size(100, 10)
        Me.ProgressBar1.TabIndex = 130
        Me.ProgressBar1.Visible = False
        '
        'Label3
        '
        Me.Label3.AutoSize = True
        Me.Label3.Location = New System.Drawing.Point(367, 305)
        Me.Label3.Name = "Label3"
        Me.Label3.Size = New System.Drawing.Size(13, 15)
        Me.Label3.TabIndex = 131
        Me.Label3.Text = "0"
        Me.Label3.Visible = False
        '
        'PictureBox1
        '
        Me.PictureBox1.BackColor = System.Drawing.SystemColors.ButtonHighlight
        Me.PictureBox1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.PictureBox1.Image = Global.QAapp.My.Resources.Resources.FA_master_v4
        Me.PictureBox1.Location = New System.Drawing.Point(13, 12)
        Me.PictureBox1.Name = "PictureBox1"
        Me.PictureBox1.Size = New System.Drawing.Size(395, 91)
        Me.PictureBox1.TabIndex = 111
        Me.PictureBox1.TabStop = False
        '
        'Timer1
        '
        Me.Timer1.Interval = 1000
        '
        'lblDeciderLogin
        '
        Me.lblDeciderLogin.AutoSize = True
        Me.lblDeciderLogin.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.lblDeciderLogin.Location = New System.Drawing.Point(357, 209)
        Me.lblDeciderLogin.Name = "lblDeciderLogin"
        Me.lblDeciderLogin.Size = New System.Drawing.Size(49, 15)
        Me.lblDeciderLogin.TabIndex = 132
        Me.lblDeciderLogin.Text = "decider"
        Me.lblDeciderLogin.Visible = False
        '
        'lblESDecider
        '
        Me.lblESDecider.AutoSize = True
        Me.lblESDecider.Location = New System.Drawing.Point(343, 224)
        Me.lblESDecider.Name = "lblESDecider"
        Me.lblESDecider.Size = New System.Drawing.Size(58, 15)
        Me.lblESDecider.TabIndex = 400
        Me.lblESDecider.Text = "ESdecider"
        Me.lblESDecider.Visible = False
        '
        'lblUserEmail
        '
        Me.lblUserEmail.AutoSize = True
        Me.lblUserEmail.Location = New System.Drawing.Point(160, 209)
        Me.lblUserEmail.Name = "lblUserEmail"
        Me.lblUserEmail.Size = New System.Drawing.Size(60, 15)
        Me.lblUserEmail.TabIndex = 401
        Me.lblUserEmail.Text = "USerEmail"
        Me.lblUserEmail.Visible = False
        '
        'lblEmailPassword
        '
        Me.lblEmailPassword.AutoSize = True
        Me.lblEmailPassword.Location = New System.Drawing.Point(243, 209)
        Me.lblEmailPassword.Name = "lblEmailPassword"
        Me.lblEmailPassword.Size = New System.Drawing.Size(86, 15)
        Me.lblEmailPassword.TabIndex = 402
        Me.lblEmailPassword.Text = "EmailPassword"
        Me.lblEmailPassword.Visible = False
        '
        'SplashScreenManager1
        '
        Me.SplashScreenManager1.ClosingDelay = 500
        '
        'DefaultLookAndFeel1
        '
        Me.DefaultLookAndFeel1.EnableBonusSkins = True
        Me.DefaultLookAndFeel1.LookAndFeel.SkinName = "The Asphalt World"
        '
        'lblRegion
        '
        Me.lblRegion.AutoSize = True
        Me.lblRegion.Location = New System.Drawing.Point(259, 234)
        Me.lblRegion.Name = "lblRegion"
        Me.lblRegion.Size = New System.Drawing.Size(44, 15)
        Me.lblRegion.TabIndex = 403
        Me.lblRegion.Text = "Region"
        Me.lblRegion.Visible = False
        '
        'LogIn
        '
        Me.AcceptButton = Me.btnLogIn
        Me.AutoScaleDimensions = New System.Drawing.SizeF(7.0!, 15.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.Color.SkyBlue
        Me.ClientSize = New System.Drawing.Size(420, 322)
        Me.Controls.Add(Me.lblRegion)
        Me.Controls.Add(Me.lblEmailPassword)
        Me.Controls.Add(Me.lblUserEmail)
        Me.Controls.Add(Me.lblESDecider)
        Me.Controls.Add(Me.lblDeciderLogin)
        Me.Controls.Add(Me.Label3)
        Me.Controls.Add(Me.ProgressBar1)
        Me.Controls.Add(Me.lblSCRN)
        Me.Controls.Add(Me.lblDrive)
        Me.Controls.Add(Me.Label2)
        Me.Controls.Add(Me.lblp)
        Me.Controls.Add(Me.lbln)
        Me.Controls.Add(Me.cboLogInNames)
        Me.Controls.Add(Me.ghost)
        Me.Controls.Add(Me.lblForgotpass)
        Me.Controls.Add(Me.btnClose)
        Me.Controls.Add(Me.Label1)
        Me.Controls.Add(Me.txtPassword)
        Me.Controls.Add(Me.txtUserName)
        Me.Controls.Add(Me.btnClear)
        Me.Controls.Add(Me.btnLogIn)
        Me.Controls.Add(Me.LinkLabel1)
        Me.Controls.Add(Me.lblPassword)
        Me.Controls.Add(Me.lblUserName)
        Me.Controls.Add(Me.PictureBox1)
        Me.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.Name = "LogIn"
        Me.Text = "FADV Quality Assurance Application Log In"
        CType(Me.PictureBox1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents PictureBox1 As System.Windows.Forms.PictureBox
    Friend WithEvents lblUserName As System.Windows.Forms.Label
    Friend WithEvents lblPassword As System.Windows.Forms.Label
    Friend WithEvents LinkLabel1 As System.Windows.Forms.LinkLabel
    Friend WithEvents btnLogIn As System.Windows.Forms.Button
    Friend WithEvents btnClear As System.Windows.Forms.Button
    Friend WithEvents txtUserName As System.Windows.Forms.TextBox
    Friend WithEvents txtPassword As System.Windows.Forms.TextBox
    Friend WithEvents Label1 As System.Windows.Forms.Label
    Friend WithEvents btnClose As System.Windows.Forms.Button
    Friend WithEvents lblForgotpass As System.Windows.Forms.LinkLabel
    Friend WithEvents ghost As System.Windows.Forms.Label
    Friend WithEvents cboLogInNames As System.Windows.Forms.ComboBox
    Friend WithEvents lbln As System.Windows.Forms.Label
    Friend WithEvents lblp As System.Windows.Forms.Label
    '  Friend WithEvents ScratchPad_DatabaseDataSet1 As ScratchPad.ScratchPad_DatabaseDataSet1
    Friend WithEvents ShowError As System.Windows.Forms.Timer
    Friend WithEvents Label2 As System.Windows.Forms.Label
    Friend WithEvents lblDrive As Label
    Friend WithEvents lblSCRN As Label
    Friend WithEvents BackgroundWorker1 As System.ComponentModel.BackgroundWorker
    Friend WithEvents ProgressBar1 As ProgressBar
    Friend WithEvents Label3 As Label
    Friend WithEvents Timer1 As Timer
    Friend WithEvents lblDeciderLogin As Label
    Friend WithEvents lblESDecider As Label
    Friend WithEvents lblUserEmail As Label
    Friend WithEvents lblEmailPassword As Label
    Friend WithEvents SplashScreenManager1 As DevExpress.XtraSplashScreen.SplashScreenManager
    Friend WithEvents DefaultLookAndFeel1 As DevExpress.LookAndFeel.DefaultLookAndFeel
    Friend WithEvents lblRegion As Label
End Class
